---
alertmanager:
  enabled: false

kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.9.6

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
