# This playbook applies the basic RBP configuration
---
  - hosts: all
    become: yes
    become_method: sudo

    roles:
    - mikolak-net.raspi_config
    - oefenweb.ufw

    tasks:
    - name: Disabling HDMI Port
      lineinfile:
        path: /etc/rc.local
        regexp: '^/usr/bin/tvservice'
        line: '/usr/bin/tvservice -o'
        insertafter: '^exit'
        state: present
