all:
  children:
    nodes:
      hosts:
        node01.local:
          ansible_user: pi
        node02.local:
          ansible_user: pi
    control:
      hosts:
        control01.local:
          ansible_user: pi
