---
global:
  image:
    repository: alinbalutoiu/argocd
    tag: linux-arm-v1.7.6

dex:
  enabled: false
  serviceAccount:
    create: false

installCRDs: false

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
